import "bootstrap/dist/css/bootstrap.min.css";
import "./css/global.css";
import "./css/typography.css";
import "./css/color.css";
import { ToastContainer } from "react-toastify";
import Header from "@/component/organisms/Header";

export const metadata = {
  title: "Tap2Sos Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        {/* <AuthProvider> */}
        {/* <RootApis /> */}

        <Header />
        {children}

        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
