import "bootstrap/dist/css/bootstrap.min.css";
import "react-modern-drawer/dist/index.css";
import "./css/global.css";
import "./css/typography.css";
import "./css/color.css";
import { ToastContainer } from "react-toastify";
import Header from "@/component/organisms/Header";
import Footer from "@/component/organisms/Footer";
import { CustomProvider } from "@/store/customProvider";
import { SocketProvider } from "@/context/SocketContext";

export const metadata = {
  title: "Tap2Sos Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <CustomProvider>
          <SocketProvider>
            <Header />
            {children}
            <Footer />
          </SocketProvider>
        </CustomProvider>
      </body>
    </html>
  );
}
